# Site settings
title: The Website of Brandon Brown
email: brandon@bybrandonbrown.com
description: Brandon's personal site where you can find references to his personal and professional work. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bybrandonbrown.com" # the base hostname & protocol for your site
twitter_username: bybrandonbrown
github_username:  brandonbrown

# Build settings
markdown: kramdown

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"